---
title: "Strava paper"
bibliography: references.bib
date: "Last compiled on `r format(Sys.time(), '%B, %Y')`"
output: 
  html_document:
    css: tweaks.css
    toc:  false
    toc_float: true
    number_sections: false
    code_folding: show
    code_download: yes
---

```{r, globalsettings, echo=FALSE, warning=FALSE}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, results="hold", message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()

colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

----  

```{r}
require(RSiena)
```

## Data sim

```{r}
networkt1 <- matrix(1, nrow=4, ncol=4)
networkt1[2,1] <- 0
networkt1[3,2] <- 0
networkt2 <- matrix(1, nrow=4, ncol=4)

sport <- c(2,1,3,3)


friendship <- sienaDependent(array( c( networkt1, networkt2), dim = c( 4,4,2 ) ) )
sport <- coCovar(sport)
mydata <- sienaDataCreate( friendship, sport )


```
## calculating the similarity scores

- maximum similarity is 1  
- maximum difference is 0  

The mean of the similarity values
```{r}

#attr(mydata$cCovars$sport, "centered")
attr(mydata$cCovars$sport, "simMean")
#mydata$cCovars$sport
```

### calculate ourselves

```{r}
rv <- attr(mydata$cCovars$sport, "range")
rv


mydata$depvars[[1]][,,1]

ego <- matrix(sport, nrow=4, ncol=4 ,byrow=FALSE)
alter <- t(ego)
ego
alter
sim <- 1 - (abs(ego-alter)/rv)
sim
diag(sim) <- NA
mean(sim, na.rm=T)

```

## avAttHigher

$$ s^{beh}_{i23}(x,z) = x^{-1}_{i+}\sum_j x_{ij} (\, I \{ (z_j + p_1)>z_i \} sim^z_{ij} + p_2*I \{ (z_j + p_1) \le z_i \} )\,$$

```{r}

ego <- 1
behavior <- "sport"
alter <- 1


fef <- function(ego, behavior, mydata) {
  beh <- mydata$cCovars[[names(mydata$cCovars)==behavior]]
  rv <- attr(mydata$cCovars[[names(mydata$cCovars)==behavior]], "range") 

egom <- matrix(mydata$cCovars[[names(mydata$cCovars)==behavior]], nrow=4, ncol=4 ,byrow=FALSE)
alterm <- t(egom)
sim <- 1 - (abs(egom-alterm)/rv)
diag(sim) <- NA

sbeh <- 0 

  for (alter in 1:length(beh)) {
    if (alter!=ego & beh[alter]>beh[ego]) sbeh <- sbeh + mydata$depvars[[1]][ego,alter,1] * sim[alter,ego] 
    if (alter!=ego & beh[alter]<=beh[ego]) sbeh <- sbeh + mydata$depvars[[1]][ego,alter,1] 
  }
  sbeh <- sbeh / (sum(mydata$depvars[[1]][ego,,1]) - 1)
 return(list(rv, sim,sbeh))
}
```

```{r}

sport <- c(2,1,3,3)
sport <- coCovar(sport)
mydata <- sienaDataCreate( friendship, sport )
fef(1, "sport", mydata)

sport <- c(3,1,3,3)
sport <- coCovar(sport)
mydata <- sienaDataCreate( friendship, sport )
fef(1, "sport", mydata)

sport <- c(1,1,3,3)
sport <- coCovar(sport)
mydata <- sienaDataCreate( friendship, sport )
fef(1, "sport", mydata)

```

Alternative operationalization

$$  s^{beh}_{i23}(x,z) = x^{-1}_{i+}\sum_j x_{ij} (\, 1 - \frac{max(z_j - z_i,0)}{r_Z})\,$$


```{r}

fef2 <- function(ego, behavior, mydata) {
  beh <- mydata$cCovars[[names(mydata$cCovars)==behavior]]
  rv <- attr(mydata$cCovars[[names(mydata$cCovars)==behavior]], "range") 

  ego <- 1
  alter <- 2
sbeh <- 0 

  for (alter in 1:length(beh)) {
    if (alter!=ego) sbeh <- sbeh + mydata$depvars[[1]][ego,alter,1] * (1 - max(beh[alter] - beh[ego],0)/rv)
    }
 sbeh <- sbeh / (sum(mydata$depvars[[1]][ego,,1]) - 1)
 return(list(rv,sbeh))
}
```


```{r}

sport <- c(2,1,3,3)
sport <- coCovar(sport)
mydata <- sienaDataCreate( friendship, sport )
fef2(1, "sport", mydata)

sport <- c(3,1,3,3)
sport <- coCovar(sport)
mydata <- sienaDataCreate( friendship, sport )
fef2(1, "sport", mydata)

sport <- c(1,1,3,3)
sport <- coCovar(sport)
mydata <- sienaDataCreate( friendship, sport )
fef2(1, "sport", mydata)

```
