---
title: "Data preparation"
bibliography: references.bib
date: "Last compiled on `r format(Sys.time(), '%B, %Y')`"
output: 
  html_document:
    css: tweaks.css
    toc:  true
    toc_float: true
    number_sections: false
    code_folding: show
    code_download: yes
---


```{r, globalsettings, echo=FALSE, warning=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()


colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```


```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```


---  



## clubdata.RData

In the following scripts a list containing the (anonymized) data of all clubs is made (clubdata.RData).


```{r eval=FALSE}
# first, install the required packages.
library(RSiena)
library(gdata)
library(psych)
library(dlookr)
library(gsubfn)
require(igraph)

# clean the working environment and set the working directory to the folder containing the scraped clubdata.
rm (list = ls( ))
setwd("C:\\YOURID\\YOURSUBID\\YOURSUBSUBDIR\\")
getwd()

# club string represents the club ID, anonymized here
club_str <- "clubid1 \n clubid2 \n clubid3 \n clubid4 \n clubid5" #enter club-IDs manually
club_str_list <- strsplit(club_str, "\n")
club_str <- as.numeric(unlist(club_str_list))

# the following script reads the data of the clubs from the folder for each club, stores them in a list, and saves it in an object in the last function call of this script. 
# we start with the first club, by assigning the first club-id from the club-string to our identifier.
# we can alter the identifier to match another club, and then re-run the script. (in the future, make a loop that does everything automatically...)

####################################################

club_id <- club_str[1] #### RESTART FROM HERE #####


{
# read the data from the club    
clubdata <- read.csv(paste(club_id, "/", "egoData_extended.csv", sep = ""), row.names = NULL, sep= ",")

# saving club size
size <- length(clubdata[, 'gender'])

# the number of months that we want to add as waves
n_waves <- 12

# separating male/female/other
male <- ifelse(clubdata[,'gender'] == "M", 1, 0)
female <- ifelse(clubdata[,'gender'] == "F", 1, 0)
other <- ifelse(clubdata[,'gender'] == "O", 1, 0)

# in case we want to condition on the first activity recorded by users:
st_yr <- clubdata[,'start_date_year']
start_year <-  ifelse(clubdata[,'start_date_year'] <= 2011, 1, st_yr)
start_year <-  ifelse(clubdata[,'start_date_year'] == 2012, 2, start_year)
start_year <-  ifelse(clubdata[,'start_date_year'] == 2013, 3, start_year)
start_year <-  ifelse(clubdata[,'start_date_year'] == 2014, 4, start_year)
start_year <-  ifelse(clubdata[,'start_date_year'] == 2015, 5, start_year)
start_year <-  ifelse(clubdata[,'start_date_year'] == 2016, 6, start_year)
start_year <-  ifelse(clubdata[,'start_date_year'] == 2017, 7, start_year)
start_year <-  ifelse(clubdata[,'start_date_year'] == 2018, 8, start_year)
start_year <-  ifelse(clubdata[,'start_date_year'] == 2019, 9, start_year)
table(start_year)

# let's load the friendship network
friend_data <- as.matrix(read.csv(paste(club_id, "/", "socialnetwork.csv", sep = ""), row.names = NULL, sep= ","))
# remove the first column (represents index made in the csv)
friend_data <- friend_data[, 2:ncol(friend_data)]
# and anonymize the user id, with an id-maker function
idmaker <- function(x)
{
  max.val = x*100000
  count <- nchar(as.character(max.val))           # find out how many 'numbers' each id will have after the letter
  size <- paste("%0",count,"d",sep="")            # set the variable to be fed into 'sprintf' to ensure we have leading 0's
  lets <- toupper(sample(letters,x, replace=T))   # randomizing the letters 
  nums <- sprintf(size,sample(1:max.val)[1:x])    # randomizing the numbers, and ensuring they all have the same number of characters
  ids <- paste(lets,nums,sep="")                  # joining them together
  return(ids)
}
fakeid <- idmaker(nrow(friend_data)) # generate random id
colnames(friend_data) <- fakeid # anonymizing users

# the following line makes a friendship network of reciprocal ties.
friend_recip <- matrix(NA, nrow = nrow(friend_data), ncol = ncol(friend_data))
for(row in 1:nrow(friend_data)) {
  for(col in 1:ncol(friend_data)) {
    value <- friend_data[row,col] * friend_data[col,row]
    friend_recip[row,col] <- value
    friend_recip[col,row] <- value
  }
}
str(friend_recip)

# let's load the kudo network
path <- paste(club_id, "/", "kudos", sep="") # create path
{
  kudo_w1 <- as.matrix(read.csv(paste(path, "1-2019.csv", sep=""), row.names = NULL, sep= ","))
  kudo_w1 <- kudo_w1[,2:ncol(kudo_w1)]
  
  kudo_w2 <- as.matrix(read.csv(paste(path, "2-2019.csv", sep=""), row.names = NULL, sep= ","))
  kudo_w2 <- kudo_w2[,2:ncol(kudo_w2)]
  
  kudo_w3 <- as.matrix(read.csv(paste(path, "3-2019.csv", sep=""), row.names = NULL, sep= ","))
  kudo_w3 <- kudo_w3[,2:ncol(kudo_w3)]
  
  kudo_w4 <- as.matrix(read.csv(paste(path, "4-2019.csv", sep=""), row.names = NULL, sep= ","))
  kudo_w4 <- kudo_w4[,2:ncol(kudo_w4)]
  
  kudo_w5 <- as.matrix(read.csv(paste(path, "5-2019.csv", sep=""), row.names = NULL, sep= ","))
  kudo_w5 <- kudo_w5[,2:ncol(kudo_w5)]
  
  kudo_w6 <- as.matrix(read.csv(paste(path, "6-2019.csv", sep=""), row.names = NULL, sep= ","))
  kudo_w6 <- kudo_w6[,2:ncol(kudo_w6)]
  
  kudo_w7 <- as.matrix(read.csv(paste(path, "7-2019.csv", sep=""), row.names = NULL, sep= ","))
  kudo_w7 <- kudo_w7[,2:ncol(kudo_w7)]
  
  kudo_w8 <- as.matrix(read.csv(paste(path, "8-2019.csv", sep=""), row.names = NULL, sep= ","))
  kudo_w8 <- kudo_w8[,2:ncol(kudo_w8)]
  
  kudo_w9 <- as.matrix(read.csv(paste(path, "9-2019.csv", sep=""), row.names = NULL, sep= ","))
  kudo_w9 <- kudo_w9[,2:ncol(kudo_w9)]
  
  kudo_w10 <- as.matrix(read.csv(paste(path, "10-2019.csv", sep=""), row.names = NULL, sep= ","))
  kudo_w10 <- kudo_w10[,2:ncol(kudo_w10)]
  
  kudo_w11 <- as.matrix(read.csv(paste(path, "11-2019.csv", sep=""), row.names = NULL, sep= ","))
  kudo_w11 <- kudo_w11[,2:ncol(kudo_w11)]
  
  kudo_w12 <- as.matrix(read.csv(paste(path, "12-2019.csv", sep=""), row.names = NULL, sep= ","))
  kudo_w12 <- kudo_w12[,2:ncol(kudo_w12)]
}
kudos <- array( c(kudo_w1,kudo_w2,kudo_w3,kudo_w4,kudo_w5,kudo_w6,kudo_w7,kudo_w8,kudo_w9,kudo_w10,kudo_w11,kudo_w12),
                  dim = c( size, size, n_waves)) #Kudo matrix

kudo_data <- ifelse(kudos > 0, 1, 0) #if at least 1 Kudo is send, give value 1

#make an ordered dependent network variable: 
#prop.table(table(kudos))

#if Kudo-exchange as a dyadic variable is at least 1, dyads are nominated for the second-order Kudo-network, in which Kudo-exchange > 3 == 1.
#dyads that are not nominated are structural zeros.
kudo_data2 <- ifelse(kudo_data == 0, NA, kudos) 
kudo_data2 <- ifelse(kudo_data2 > 3, 1, 0)
kudo_data2 <- ifelse(is.na(kudo_data2), 10, kudo_data2) #turn NA's into structural zeros (10s)

#if Kudo-exchange as a dyadic variable is at least 2, dyads are nominated for the third-order Kudo-network, in which Kudo-exchange > 7 == 1.
#dyads that are not nominated are structural zeros.
kudo_data3 <- ifelse(kudo_data == 0, NA, ifelse(kudo_data2 == 0, NA, kudos)) 
kudo_data3 <- ifelse(kudo_data3 > 7, 1, 0)
kudo_data3 <- ifelse(is.na(kudo_data3), 10, kudo_data3) #turn NA's into structural zeros (10s)

#for now, these order cut-offs were quite arbitrarily chosen; can be extended, or be applied with other categories.

# let's load the behavioral data
# running time
time_run <- array( c( clubdata[, 'time_run_1.2019'], clubdata[, 'time_run_2.2019'], clubdata[, 'time_run_3.2019'], clubdata[, 'time_run_4.2019'], clubdata[, 'time_run_5.2019'], clubdata[, 'time_run_6.2019'], clubdata[, 'time_run_7.2019'], clubdata[, 'time_run_8.2019'], clubdata[, 'time_run_9.2019'], clubdata[, 'time_run_10.2019'], clubdata[, 'time_run_11.2019'], clubdata[, 'time_run_12.2019']),
                   dim = c( size, 1, n_waves ) )
str(time_run)

# we cluster the time into 8 categories (from 0 to 7, with 0 being 0 minutes)
# this is Manuel's clustering
# follow recommendations by Snijders and colleaugues (see RSiena manual),
# and specifically check dissertation bij Niezink (Chapter 6):
# smooth (skew) distribution of values / or equally populated categories (cf. Flashman 2012)
time_run_temp <- ifelse(time_run > 0 & time_run <= 120, 1, time_run)
time_run_temp <- ifelse(time_run > 120 & time_run <= 240, 2, time_run_temp)
time_run_temp <- ifelse(time_run > 240 & time_run <= 360, 3, time_run_temp)
time_run_temp <- ifelse(time_run > 360 & time_run <= 480, 4, time_run_temp)
time_run_temp <- ifelse(time_run > 480 & time_run <= 600, 5, time_run_temp)
time_run_temp <- ifelse(time_run > 600 & time_run <= 720, 6, time_run_temp)
time_run_temp <- ifelse(time_run > 720, 7, time_run_temp)
#table(time_run_temp) #minutes per month
#hist(time_run_temp)

# running frequency
# here a categorization for 0-7 times a week makes sense, theoretically
# and gives a smoothly right-skewed distribution
# clubs may differ in their (average) activity levels: in some an substantial proportion 
# runs more than 7 times (thus more than once a day)... add an 9th category for these clubs?
freq_run <- array( c( clubdata[, 'X.run_1.2019'], clubdata[, 'X.run_2.2019'], clubdata[, 'X.run_3.2019'], clubdata[, 'X.run_4.2019'], clubdata[, 'X.run_5.2019'], clubdata[, 'X.run_6.2019'], clubdata[, 'X.run_7.2019'], clubdata[, 'X.run_8.2019'], clubdata[, 'X.run_9.2019'], clubdata[, 'X.run_10.2019'], clubdata[, 'X.run_11.2019'], clubdata[, 'X.run_12.2019']),
                dim = c( size, 1, n_waves ) )
frequencies <- ceiling(freq_run/4)
freq_run_temp <- ifelse(frequencies > 7, 7, frequencies) 
#freq_run_temp <- ifelse(frequencies > 7, 8, frequencies) #extra category?
#table(freq_run_temp) #days a week

# now that we have running data, let's load cycling data
# time
time_ride <- array( c( clubdata[, 'time_ride_1.2019'], clubdata[, 'time_ride_2.2019'], clubdata[, 'time_ride_3.2019'], clubdata[, 'time_ride_4.2019'], clubdata[, 'time_ride_5.2019'], clubdata[, 'time_ride_6.2019'], clubdata[, 'time_ride_7.2019'], clubdata[, 'time_ride_8.2019'], clubdata[, 'time_ride_9.2019'], clubdata[, 'time_ride_10.2019'], clubdata[, 'time_ride_11.2019'], clubdata[, 'time_ride_12.2019']),
                    dim = c( size, 1, n_waves ) )
time_ride_temp <- ifelse(time_ride > 0 & time_ride <= 120, 1, time_ride)
time_ride_temp <- ifelse(time_ride > 120 & time_ride <= 240, 2, time_ride_temp)
time_ride_temp <- ifelse(time_ride > 240 & time_ride <= 360, 3, time_ride_temp)
time_ride_temp <- ifelse(time_ride > 360 & time_ride <= 480, 4, time_ride_temp)
time_ride_temp <- ifelse(time_ride > 480 & time_ride <= 600, 5, time_ride_temp)
time_ride_temp <- ifelse(time_ride > 600 & time_ride <= 720, 6, time_ride_temp)
time_ride_temp <- ifelse(time_ride > 720, 7, time_ride_temp)
#table(time_ride_temp) #minutes per month
#hist(time_run_temp)  

# frequency
freq_ride <- array( c( clubdata[, 'X.ride_1.2019'], clubdata[, 'X.ride_2.2019'], clubdata[, 'X.ride_3.2019'], clubdata[, 'X.ride_4.2019'], clubdata[, 'X.ride_5.2019'], clubdata[, 'X.ride_6.2019'], clubdata[, 'X.ride_7.2019'], clubdata[, 'X.ride_8.2019'], clubdata[, 'X.ride_9.2019'], clubdata[, 'X.ride_10.2019'], clubdata[, 'X.ride_11.2019'], clubdata[, 'X.ride_12.2019']),
                    dim = c( size, 1, n_waves ) )
frequencies <- ceiling(freq_ride/4)
freq_ride_temp <- ifelse(frequencies > 7, 7, frequencies)
#freq_ride_temp <- ifelse(frequencies > 7, 8, frequencies) #extra category?
#table(freq_ride_temp) #days a week

# and 'other' activities
# time
time_other <- array( c( clubdata[, 'time_other_1.2019'], clubdata[, 'time_other_2.2019'], clubdata[, 'time_other_3.2019'], clubdata[, 'time_other_4.2019'], clubdata[, 'time_other_5.2019'], clubdata[, 'time_other_6.2019'], clubdata[, 'time_other_7.2019'], clubdata[, 'time_other_8.2019'], clubdata[, 'time_other_9.2019'], clubdata[, 'time_other_10.2019'], clubdata[, 'time_other_11.2019'], clubdata[, 'time_other_12.2019']),
                     dim = c( size, 1, n_waves ) )
time_other_temp <- ifelse(time_other > 0 & time_other <= 120, 1, time_other)
time_other_temp <- ifelse(time_other > 120 & time_other <= 240, 2, time_other_temp)
time_other_temp <- ifelse(time_other > 240 & time_other <= 360, 3, time_other_temp)
time_other_temp <- ifelse(time_other > 360 & time_other <= 480, 4, time_other_temp)
time_other_temp <- ifelse(time_other > 480 & time_other <= 600, 5, time_other_temp)
time_other_temp <- ifelse(time_other > 600 & time_other <= 720, 6, time_other_temp)
time_other_temp <- ifelse(time_other > 720, 7, time_other_temp)
#table(time_other_temp) #minutes per month
#hist(time_other_temp)  

# frequency
freq_other <- array( c( clubdata[, 'X.other_1.2019'], clubdata[, 'X.other_2.2019'], clubdata[, 'X.other_3.2019'], clubdata[, 'X.other_4.2019'], clubdata[, 'X.other_5.2019'], clubdata[, 'X.other_6.2019'], clubdata[, 'X.other_7.2019'], clubdata[, 'X.other_8.2019'], clubdata[, 'X.other_9.2019'], clubdata[, 'X.other_10.2019'], clubdata[, 'X.other_11.2019'], clubdata[, 'X.other_12.2019']),
                     dim = c( size, 1, n_waves ) )
frequencies <- ceiling(freq_other/4)
freq_other_temp <- ifelse(frequencies > 7, 7, frequencies)
#freq_other_temp <- ifelse(frequencies > 7, 8, frequencies) #extra category?
#table(freq_other_temp) #days a week

# specify months of winter in case we want to use it as a varying covariate
# starts with december?
winter <- rep(c(1,1,1,0,0,0,0,0,0,0,0,0), size)
winter <- matrix(winter,nrow = size,ncol = n_waves, byrow = TRUE)

# create a list containing all the read club data for club 1
club <- list("friendship" = friend_data, 
             "kudo" = kudo_data, "kudo2" = kudo_data2, "kudo3" = kudo_data3,
             "freq_run" = freq_run_temp, "time_run" = time_run_temp, "freq_ride" = freq_ride_temp, "time_ride" = time_ride_temp, "freq_other" = freq_other_temp, "time_other" = time_other_temp, "winter" = winter, "male" = male, "female" = female, "other" = other, "netsize" = size, "startyear" = st_yr)

# and restart from line 35
}

# save it in the working directory folder
save(club, file=paste("club", club_id, ".RData", sep = ""))

####################################################

# Now that we have saved the clubdata for all clubs, let's combine them in one list

# first clean the working directory
rm (list = ls( ))

# load in the separate club-objects
{
  club1 <- load("clubclubid1.RData")
  club1 <- club
  
  club2 <- load("clubclubid2.RData")
  club2 <- club
  
  club3 <- load("clubclubid2.RData")
  club3 <- club
  
  club4 <- load("clubclubid4.RData")
  club4 <- club
  
  club5 <- load("clubclubid5.RData")
  club5 <- club
}
# and make a list containing all the clubdata
clubdata <- list(club1, club2, club3, club4, club5)

# save the output
save(clubdata, file="clubdata.RData")

# end.

``` 

---  

## clubdata_rsiena.RData

The following script creates a list containing RSiena objects for all clubs (clubdata_rsiena.RData).

```{r eval=FALSE}
# install RSiena
library(RSiena)

# clean the working environment 
# set the working directory to the folder containing the clubdata (clubdata.RData)
rm (list = ls( ))
setwd("C:\\YOURID\\YOURSUBID\\YOURSUBSUBDIR\\")
getwd()

# load the clubdata
load("clubdata.RData")
str(clubdata) # inspect structure
# clubdata is a list of 5 lists, 
# with each of these lists containing data of the corresponding club.

# the following script will make a RSiena object.
# again, we start with the first club.
# the script can be re-run after pulling from the list the data of another club (and so forth...)
# eventually, we will combine the output into a list containing the RSiena objects of all the clubs.

####################################################

club <- clubdata[[1]] #### RESTART FROM HERE #####


{ 
  # specify the roles of variables
  names(club)
  
  # A: dependent variables
  kudonet <- sienaDependent(club$kudo) #at least one Kudo
  kudonet2 <- sienaDependent(club$kudo2) #>3 Kudos
  kudonet3 <- sienaDependent(club$kudo3) #>7 Kudos
  time_run <- sienaDependent(club$time_run, type= "behavior")
  freq_run <- sienaDependent(club$freq_run, type= "behavior")
  time_ride <- sienaDependent(club$time_ride, type= "behavior")
  freq_ride <- sienaDependent(club$freq_ride, type= "behavior")
  time_other <- sienaDependent(club$time_other, type= "behavior")
  freq_other <- sienaDependent(club$freq_other, type= "behavior")
  
  # B: explanatory variables
  friendship <- coDyadCovar(club$friendship)
  winter <- varCovar(club$winter)
  male <- coCovar(club$male)
  female <- coCovar(club$female)
  other <- coCovar(club$other)
  
  # now combine the dependent and independent variables in a data object
  mydata <- sienaDataCreate(kudonet, kudonet2, kudonet3,  time_run, freq_run, time_ride, freq_ride, time_other, freq_other, friendship, winter, male, female, other)
  mydata 
  
  # this finishes the data specification
} 

# save the RSiena object and restart the process from line 33.
rsienadataobjectclub_1 <- mydata # adjust number to match the corresponding club number

####################################################

# now make a list containing all the RSiena data objects
clubdata_rsiena <- list(rsienadataobjectclub_1, rsienadataobjectclub_2, rsienadataobjectclub_3, rsienadataobjectclub_4, rsienadataobjectclub_5)

# add netsize
{
  clubdata_rsiena[[1]]$netsize <- clubdata[[1]]$netsize
  clubdata_rsiena[[2]]$netsize <- clubdata[[2]]$netsize
  clubdata_rsiena[[3]]$netsize <- clubdata[[3]]$netsize
  clubdata_rsiena[[4]]$netsize <- clubdata[[4]]$netsize
  clubdata_rsiena[[5]]$netsize <- clubdata[[5]]$netsize
}

# save the output
save(clubdata_rsiena, file="clubdata_rsiena.RData")
```

---  

